version: '3.9'

services:
  db_host:
    image: mysql
    # ports:
    #   - '3306:3306'
    restart: always
    environment:
      MYSQL_DATABASE: 'mysql_django'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    healthcheck:
      # test: "mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD"
      test: "mysqladmin ping --silent"
      interval: 1s
      timeout: 1s
      retries: 1
      start_period: 4s
    volumes:
      - mysql_data:/var/lib/mysql:rw
  
  django:
    # build: .
    image: ghcr.io/samhitha18/mysql-docker:latest
    command: bash -c "python3 project1/manage.py makemigrations sqlDjango && python3 project1/manage.py migrate && python3 project1/manage.py runserver 0.0.0.0:8200"
    restart: always
    ports:
      - '8989:8200'
    depends_on:
      db_host:
        condition: service_healthy
volumes:
  mysql_data: